services:
  db:
    container_name: fundforge_db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
